# base path
server.servlet.context-path: /api/v1

# enable H2 console
spring.h2.console.enabled: true
spring.datasource.platform: h2
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.url: jdbc:h2:mem:po
spring.datasource.username: sa
spring.datasource.password:

# log levels
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO