# api base path
server:
  servlet:
    context-path: /api/v1

# enable H2 (in-memory db) console
spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:po
    username: sa
    password:

# oauth2 resource server config - jwt verification
# verify signature, issuer and audience
security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://jv-techex.auth0.com/.well-known/jwks.json

# log levels
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO

